SinatraメモアプリDB接続版を作成いたしました。
junohm410/sinatra-practice-memoapp pull request #2
Opened 2023-08-09 12:26 UTC by junohm410

SinatraメモアプリDB接続版を作成いたしました。
レビューのほど、何卒よろしくお願い致します🙏

## メモ保管用のDB作成のSQL分
READMEにも記載しましたが、下記のとおりです。
```sql
# memo DBを作成
CREATE DATABASE memo;

# memo テーブルを作成
CREATE TABLE memo (
  id CHAR(36) NOT NULL,
  title VARCHAR(100) NOT NULL,
  text VARCHAR(1000) NOT NULL,
  added_time TIMESTAMP NOT NULL,
  PRIMARY KEY (id));
```

## 不明瞭なまま進めている点
### メモ保存時の日付取得について
#### 疑問
- DBにレコードを挿入する際に、SQL関数を用いることは問題ないのか
#### なぜその疑問を持ったか
メモを追加日時順に並べるために、memoテーブルに日付のカラム`added_time`を用意しました。
メモ追加時に、SQL関数`CURRENT_TIMESTAMP`で日付を挿入する形にしています。

```ruby
post '/memos' do
  id = SecureRandom.uuid
  conn = PG.connect(dbname: 'memo')
  conn.exec_params('INSERT INTO memo VALUES ($1, $2, $3, CURRENT_TIMESTAMP)', [id, params[:title], params[:content]])
  conn.finish
  redirect to('/memos')
end
```
このように実装を進めたあと、SQL部分の実装について参考にした『SQL 第2版 ゼロからはじめるデータベース操作』の当該関数の部分をよく読むと、`CURRENT_TIMESTAMP`は
> 『SQLServerを含めた主要DBMSのすべてで使うことができる』

が、
> 『ただし、CURRENT_DATEやCURRENT_TIMEのときと同じく、OracleとDB2では少し構文が異なります。』

と記載があることに気づきました。

Rubyで追加時間を取得してDBのフォーマットに変換せずに、この関数でデータを挿入できるなら便利かなと考えましたが、このように方言の違いが起きる可能性がある場合は、「使用するRDBMSを限定するような状況でなければこのような実装は避ける」、ということになるのでしょうか。
また、方言的なリスク以外に、アプリ側からクエリを発行する際にSQL関数を使用することのリスクが何かあったりしますでしょうか？

今回の課題では、DBがPostgreSQLに指定されており、`pg`を導入しての実装なので、いったん上記の実装で提出いたします。
誤認点や問題点、修正すべき点がありましたらご指摘いただけると幸いでございます🙇‍♂️
よろしくお願いいたします🙏

2023-08-15 01:16 UTC, u1tnk commented
> Rubyで追加時間を取得 -> DB側のフォーマットに変換 の工程を経ず、SQL関数でデータを挿入できるなら便利かなと考えましたが、上記の方言的な問題に、アプリ側からクエリを発行する際にSQL関数を使用することのリスクは何かあったりしますでしょうか？（パフォーマンスの問題などがありそう？）

問題無いです。以下蛇足ですが説明です。

`CURRENT_TIMESTAMP` を使うのが昔は一般的でした。
使い方はちょっと違っていて、こういう作成日時などの場合は create table時点で default値として設定しておきます。

複数サーバが当然の本番環境では厳密には時間もズレることがあるし、追加時に時間設定する手間が減るという感じでした。
現在はインフラの進歩で時間のズレはほぼ無いですし、railsが勝手に入れてくれたりするので一般的では無いですが、直にSQLを書くときは使う事もありますね。

2023-08-15 01:23 UTC, u1tnk requested changes

2023-08-15 01:23 UTC, u1tnk commented on memo_app.rb
> +  conn = PG.connect(dbname: 'memo')
> DB接続は遅い(重い)処理なので使い回せるようにしよう。

こちらが対応されてなさそうなので対応お願いします。

2023-08-15 01:23 UTC, u1tnk commented on memo_app.rb
> +  id = SecureRandom.uuid
idはDBを使うのであればDBに採番を任せましょう。

2023-08-15 09:17 UTC, junohm410 commented on memo_app.rb
> +  conn = PG.connect(dbname: 'memo')
こちらご指摘ありがとうございます。「使いまわす」の意味を「1リクエストの中で接続は1回まで」と勘違いしていました🙇‍♂️
トップレベルで`PG.connect`の値を定数に代入し、アプリ起動時に接続したオブジェクトを使い回すような形に修正してみました。

初回の提出物の場合、各リクエストの最後に接続を切断（`conn.finish`）していましたが、今回は「明示的に接続を切るべきなのか、また切るとすればどこにどう書くべきか」ということについて、正直自信がありません……🙇‍♂️

自分で考えたこと
- 明示的に切断をしなくても、`Control + C`でサーバーを止めてアプリを終了するのはDBサーバーとの切断を伴うので、それをする必要がないのかなとも思いました。
- ただし、たとえば「ブラウザでメモアプリのタブだけ閉じるけど、またあとで使う時のためにコンソールでのアプリそのものは終了しない」というときに、「アプリは使われていないけれど（サーバーとは繋がっている）、DBとの接続は切れていない」状態が維持されると思います。
たとえばこんな状況が問題とされるべきなのかどうかが、よくわかっていないような気がします……。

いったん明示的にDBとの接続を切る処理を書かずに提出しておりますが、問題点や上記の部分で誤認点があればご指摘いただけると大変ありがたいです。
よろしくお願いいたします🙏

2023-08-15 09:19 UTC, junohm410 commented
レビュー、ありがとうございました。

> 問題無いです。以下蛇足ですが説明です。
>
> CURRENT_TIMESTAMP を使うのが昔は一般的でした。
> 使い方はちょっと違っていて、こういう作成日時などの場合は create table時点で default値として設定しておきます。

こちらご回答ありがとうございました🙇‍♂️
そして使うにしてもテーブル作成時にdefaultにすればより手間も省けるというのは、自分では気づけませんでした🙏とても納得です。
今Railsの参考書を少しずつ読んでいますが、たしかに登録日時の発行はRailsにお任せしているようだったので、その意味でも教えていただいた内容を理解できたと思います。
いったん、この内容にならって`create table`段階でデフォルトで登録日時を関数で取得できるよう修正しました。

接続を使いまわさない、という部分に関しては、いただいたコメントに返信する形で修正内容と疑問点を書かせていただきました🙇‍♂️

ご確認のほど、何卒宜しくお願いいたします🙏

2023-08-15 14:38 UTC, u1tnk requested changes
あと細かいところ一点対応お願いします 🙏

2023-08-15 14:38 UTC, u1tnk commented on memo_app.rb
> +CONN = PG.connect(dbname: 'memo')
起動時に格納するにしても定数ではなく変数にしましょう。
定数にするのは基本的には文字列、数値のみと思ってください。

2023-08-15 14:38 UTC, u1tnk commented on memo_app.rb
> +  conn = PG.connect(dbname: 'memo')
どんどん接続が増えていくのは良くないので 切断が必須ですが、この書き方なら sinatraプロセス一つにつき一つになるはずなので問題ありません。sinatraプロセスが落ちるときには切断されます。

2023-08-15 15:39 UTC, junohm410 commented
再レビュー、ありがとうございました🙏
切断の件も、ご回答ありがとうございます🙇‍♂️

今回の場合はSinatraの1プロセスの中で接続数自体がどんどん増えるわけではないという点で問題ないということ、承知しました。
逆に言えば、接続数そのものがどんどんと増えていきかねない状況の場合は、接続の数を意識してコントロールする必要がある、というイメージなのかなと想像しました。
（もしかしたらそれはフレームワークがうまくやってくれることなのかもしれませんが）今後の学習を進める中で意識してみたいと思います！

また定数の件、ご指摘ありがとうございます🙇‍♂️
> 定数にするのは基本的には文字列、数値のみと思ってください。

承知しました、気をつけます……🙏
変数に`PG.connect`で取得するオブジェクトを代入し、各ルーティング（と途中に使うメソッド）で使うように修正しました。

ご確認のほど、よろしくお願い致します🙇‍♂️

2023-08-16 13:19 UTC, u1tnk approved these changes

2023-08-16 13:25 UTC, u1tnk commented
approveしました！

> （もしかしたらそれはフレームワークがうまくやってくれることなのかもしれませんが）今後の学習を進める中で意識してみたいと思います！

はい、一般に ConnectionPoolという名前で存在します。Railsにもありますね。
気になったら調べてみてください 💪

2023-08-17 02:47 UTC, merged